# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .flat_object import FlatObject
from .nested_object import NestedObject
from ._test_model_single_dict import TestModelSingleDict
from . import util


class TestModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    openapi_types = {
        'single_str': str,
        'single_complex': str,
        'single_int': int,
        'single_float': float,
        'single_bool': bool,
        'single_uuid': str,
        'single_date': date,
        'single_datetime': datetime,
        'single_enum': str,
        'single_dict': TestModelSingleDict,
        'flat_object': FlatObject,
        'nested_object': NestedObject,
        'list_of_flat_objects': List[FlatObject],
        'list_of_nested_objects': List[NestedObject],
        'list_of_str': List[str],
        'list_of_int': List[int],
        'list_of_float': List[float],
        'tuple_of_str': List[str],
        'tuple_of_int': List[int],
        'tuple_of_float': List[float],
        'set_of_str': List[str],
        'set_of_int': List[int],
        'set_of_float': List[float],
    }

    attribute_map = {
        'single_str': 'single_str',
        'single_complex': 'single_complex',
        'single_int': 'single_int',
        'single_float': 'single_float',
        'single_bool': 'single_bool',
        'single_uuid': 'single_uuid',
        'single_date': 'single_date',
        'single_datetime': 'single_datetime',
        'single_enum': 'single_enum',
        'single_dict': 'single_dict',
        'flat_object': 'flat_object',
        'nested_object': 'nested_object',
        'list_of_flat_objects': 'list_of_flat_objects',
        'list_of_nested_objects': 'list_of_nested_objects',
        'list_of_str': 'list_of_str',
        'list_of_int': 'list_of_int',
        'list_of_float': 'list_of_float',
        'tuple_of_str': 'tuple_of_str',
        'tuple_of_int': 'tuple_of_int',
        'tuple_of_float': 'tuple_of_float',
        'set_of_str': 'set_of_str',
        'set_of_int': 'set_of_int',
        'set_of_float': 'set_of_float',
    }

    def __init__(
        self,
        single_str='string',
        single_complex='123',
        single_int=123,
        single_float=123.45,
        single_bool=False,
        single_uuid='fb4932cc-f9c2-4507-bdcf-5b5e5cee3135',
        single_date=None,
        single_datetime=None,
        single_enum='FIRST',
        single_dict=None,
        flat_object=None,
        nested_object=None,
        list_of_flat_objects=[],
        list_of_nested_objects=[],
        list_of_str=[],
        list_of_int=[],
        list_of_float=[],
        tuple_of_str=[],
        tuple_of_int=[],
        tuple_of_float=[],
        set_of_str=[],
        set_of_int=[],
        set_of_float=[],
    ):  # noqa: E501
        """TestModel - a model defined in OpenAPI

        :param single_str: The single_str of this TestModel.  # noqa: E501
        :type single_str: str
        :param single_complex: The single_complex of this TestModel.  # noqa: E501
        :type single_complex: str
        :param single_int: The single_int of this TestModel.  # noqa: E501
        :type single_int: int
        :param single_float: The single_float of this TestModel.  # noqa: E501
        :type single_float: float
        :param single_bool: The single_bool of this TestModel.  # noqa: E501
        :type single_bool: bool
        :param single_uuid: The single_uuid of this TestModel.  # noqa: E501
        :type single_uuid: str
        :param single_date: The single_date of this TestModel.  # noqa: E501
        :type single_date: date
        :param single_datetime: The single_datetime of this TestModel.  # noqa: E501
        :type single_datetime: datetime
        :param single_enum: The single_enum of this TestModel.  # noqa: E501
        :type single_enum: str
        :param single_dict: The single_dict of this TestModel.  # noqa: E501
        :type single_dict: TestModelSingleDict
        :param flat_object: The flat_object of this TestModel.  # noqa: E501
        :type flat_object: FlatObject
        :param nested_object: The nested_object of this TestModel.  # noqa: E501
        :type nested_object: NestedObject
        :param list_of_flat_objects: The list_of_flat_objects of this TestModel.  # noqa: E501
        :type list_of_flat_objects: List[FlatObject]
        :param list_of_nested_objects: The list_of_nested_objects of this TestModel.  # noqa: E501
        :type list_of_nested_objects: List[NestedObject]
        :param list_of_str: The list_of_str of this TestModel.  # noqa: E501
        :type list_of_str: List[str]
        :param list_of_int: The list_of_int of this TestModel.  # noqa: E501
        :type list_of_int: List[int]
        :param list_of_float: The list_of_float of this TestModel.  # noqa: E501
        :type list_of_float: List[float]
        :param tuple_of_str: The tuple_of_str of this TestModel.  # noqa: E501
        :type tuple_of_str: List[str]
        :param tuple_of_int: The tuple_of_int of this TestModel.  # noqa: E501
        :type tuple_of_int: List[int]
        :param tuple_of_float: The tuple_of_float of this TestModel.  # noqa: E501
        :type tuple_of_float: List[float]
        :param set_of_str: The set_of_str of this TestModel.  # noqa: E501
        :type set_of_str: List[str]
        :param set_of_int: The set_of_int of this TestModel.  # noqa: E501
        :type set_of_int: List[int]
        :param set_of_float: The set_of_float of this TestModel.  # noqa: E501
        :type set_of_float: List[float]
        """

        self.single_str = single_str
        self.single_complex = single_complex
        self.single_int = single_int
        self.single_float = single_float
        self.single_bool = single_bool
        self.single_uuid = single_uuid
        self.single_date = single_date
        self.single_datetime = single_datetime
        self.single_enum = single_enum
        self.single_dict = single_dict
        self.flat_object = flat_object
        self.nested_object = nested_object
        self.list_of_flat_objects = list_of_flat_objects
        self.list_of_nested_objects = list_of_nested_objects
        self.list_of_str = list_of_str
        self.list_of_int = list_of_int
        self.list_of_float = list_of_float
        self.tuple_of_str = tuple_of_str
        self.tuple_of_int = tuple_of_int
        self.tuple_of_float = tuple_of_float
        self.set_of_str = set_of_str
        self.set_of_int = set_of_int
        self.set_of_float = set_of_float

    @classmethod
    def from_dict(cls, dikt) -> 'TestModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TestModel of this TestModel.  # noqa: E501
        :rtype: TestModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def single_str(self):
        """Gets the single_str of this TestModel.


        :return: The single_str of this TestModel.
        :rtype: str
        """
        return self._single_str

    @single_str.setter
    def single_str(self, single_str):
        """Sets the single_str of this TestModel.


        :param single_str: The single_str of this TestModel.
        :type single_str: str
        """

        self._single_str = single_str

    @property
    def single_complex(self):
        """Gets the single_complex of this TestModel.


        :return: The single_complex of this TestModel.
        :rtype: str
        """
        return self._single_complex

    @single_complex.setter
    def single_complex(self, single_complex):
        """Sets the single_complex of this TestModel.


        :param single_complex: The single_complex of this TestModel.
        :type single_complex: str
        """

        self._single_complex = single_complex

    @property
    def single_int(self):
        """Gets the single_int of this TestModel.


        :return: The single_int of this TestModel.
        :rtype: int
        """
        return self._single_int

    @single_int.setter
    def single_int(self, single_int):
        """Sets the single_int of this TestModel.


        :param single_int: The single_int of this TestModel.
        :type single_int: int
        """

        self._single_int = single_int

    @property
    def single_float(self):
        """Gets the single_float of this TestModel.


        :return: The single_float of this TestModel.
        :rtype: float
        """
        return self._single_float

    @single_float.setter
    def single_float(self, single_float):
        """Sets the single_float of this TestModel.


        :param single_float: The single_float of this TestModel.
        :type single_float: float
        """

        self._single_float = single_float

    @property
    def single_bool(self):
        """Gets the single_bool of this TestModel.


        :return: The single_bool of this TestModel.
        :rtype: bool
        """
        return self._single_bool

    @single_bool.setter
    def single_bool(self, single_bool):
        """Sets the single_bool of this TestModel.


        :param single_bool: The single_bool of this TestModel.
        :type single_bool: bool
        """

        self._single_bool = single_bool

    @property
    def single_uuid(self):
        """Gets the single_uuid of this TestModel.


        :return: The single_uuid of this TestModel.
        :rtype: str
        """
        return self._single_uuid

    @single_uuid.setter
    def single_uuid(self, single_uuid):
        """Sets the single_uuid of this TestModel.


        :param single_uuid: The single_uuid of this TestModel.
        :type single_uuid: str
        """

        self._single_uuid = single_uuid

    @property
    def single_date(self):
        """Gets the single_date of this TestModel.


        :return: The single_date of this TestModel.
        :rtype: date
        """
        return self._single_date

    @single_date.setter
    def single_date(self, single_date):
        """Sets the single_date of this TestModel.


        :param single_date: The single_date of this TestModel.
        :type single_date: date
        """

        self._single_date = single_date

    @property
    def single_datetime(self):
        """Gets the single_datetime of this TestModel.


        :return: The single_datetime of this TestModel.
        :rtype: datetime
        """
        return self._single_datetime

    @single_datetime.setter
    def single_datetime(self, single_datetime):
        """Sets the single_datetime of this TestModel.


        :param single_datetime: The single_datetime of this TestModel.
        :type single_datetime: datetime
        """

        self._single_datetime = single_datetime

    @property
    def single_enum(self):
        """Gets the single_enum of this TestModel.


        :return: The single_enum of this TestModel.
        :rtype: str
        """
        return self._single_enum

    @single_enum.setter
    def single_enum(self, single_enum):
        """Sets the single_enum of this TestModel.


        :param single_enum: The single_enum of this TestModel.
        :type single_enum: str
        """

        self._single_enum = single_enum

    @property
    def single_dict(self):
        """Gets the single_dict of this TestModel.


        :return: The single_dict of this TestModel.
        :rtype: TestModelSingleDict
        """
        return self._single_dict

    @single_dict.setter
    def single_dict(self, single_dict):
        """Sets the single_dict of this TestModel.


        :param single_dict: The single_dict of this TestModel.
        :type single_dict: TestModelSingleDict
        """

        self._single_dict = single_dict

    @property
    def flat_object(self):
        """Gets the flat_object of this TestModel.


        :return: The flat_object of this TestModel.
        :rtype: FlatObject
        """
        return self._flat_object

    @flat_object.setter
    def flat_object(self, flat_object):
        """Sets the flat_object of this TestModel.


        :param flat_object: The flat_object of this TestModel.
        :type flat_object: FlatObject
        """

        self._flat_object = flat_object

    @property
    def nested_object(self):
        """Gets the nested_object of this TestModel.


        :return: The nested_object of this TestModel.
        :rtype: NestedObject
        """
        return self._nested_object

    @nested_object.setter
    def nested_object(self, nested_object):
        """Sets the nested_object of this TestModel.


        :param nested_object: The nested_object of this TestModel.
        :type nested_object: NestedObject
        """

        self._nested_object = nested_object

    @property
    def list_of_flat_objects(self):
        """Gets the list_of_flat_objects of this TestModel.


        :return: The list_of_flat_objects of this TestModel.
        :rtype: List[FlatObject]
        """
        return self._list_of_flat_objects

    @list_of_flat_objects.setter
    def list_of_flat_objects(self, list_of_flat_objects):
        """Sets the list_of_flat_objects of this TestModel.


        :param list_of_flat_objects: The list_of_flat_objects of this TestModel.
        :type list_of_flat_objects: List[FlatObject]
        """

        self._list_of_flat_objects = list_of_flat_objects

    @property
    def list_of_nested_objects(self):
        """Gets the list_of_nested_objects of this TestModel.


        :return: The list_of_nested_objects of this TestModel.
        :rtype: List[NestedObject]
        """
        return self._list_of_nested_objects

    @list_of_nested_objects.setter
    def list_of_nested_objects(self, list_of_nested_objects):
        """Sets the list_of_nested_objects of this TestModel.


        :param list_of_nested_objects: The list_of_nested_objects of this TestModel.
        :type list_of_nested_objects: List[NestedObject]
        """

        self._list_of_nested_objects = list_of_nested_objects

    @property
    def list_of_str(self):
        """Gets the list_of_str of this TestModel.


        :return: The list_of_str of this TestModel.
        :rtype: List[str]
        """
        return self._list_of_str

    @list_of_str.setter
    def list_of_str(self, list_of_str):
        """Sets the list_of_str of this TestModel.


        :param list_of_str: The list_of_str of this TestModel.
        :type list_of_str: List[str]
        """

        self._list_of_str = list_of_str

    @property
    def list_of_int(self):
        """Gets the list_of_int of this TestModel.


        :return: The list_of_int of this TestModel.
        :rtype: List[int]
        """
        return self._list_of_int

    @list_of_int.setter
    def list_of_int(self, list_of_int):
        """Sets the list_of_int of this TestModel.


        :param list_of_int: The list_of_int of this TestModel.
        :type list_of_int: List[int]
        """

        self._list_of_int = list_of_int

    @property
    def list_of_float(self):
        """Gets the list_of_float of this TestModel.


        :return: The list_of_float of this TestModel.
        :rtype: List[float]
        """
        return self._list_of_float

    @list_of_float.setter
    def list_of_float(self, list_of_float):
        """Sets the list_of_float of this TestModel.


        :param list_of_float: The list_of_float of this TestModel.
        :type list_of_float: List[float]
        """

        self._list_of_float = list_of_float

    @property
    def tuple_of_str(self):
        """Gets the tuple_of_str of this TestModel.


        :return: The tuple_of_str of this TestModel.
        :rtype: List[str]
        """
        return self._tuple_of_str

    @tuple_of_str.setter
    def tuple_of_str(self, tuple_of_str):
        """Sets the tuple_of_str of this TestModel.


        :param tuple_of_str: The tuple_of_str of this TestModel.
        :type tuple_of_str: List[str]
        """

        self._tuple_of_str = tuple_of_str

    @property
    def tuple_of_int(self):
        """Gets the tuple_of_int of this TestModel.


        :return: The tuple_of_int of this TestModel.
        :rtype: List[int]
        """
        return self._tuple_of_int

    @tuple_of_int.setter
    def tuple_of_int(self, tuple_of_int):
        """Sets the tuple_of_int of this TestModel.


        :param tuple_of_int: The tuple_of_int of this TestModel.
        :type tuple_of_int: List[int]
        """

        self._tuple_of_int = tuple_of_int

    @property
    def tuple_of_float(self):
        """Gets the tuple_of_float of this TestModel.


        :return: The tuple_of_float of this TestModel.
        :rtype: List[float]
        """
        return self._tuple_of_float

    @tuple_of_float.setter
    def tuple_of_float(self, tuple_of_float):
        """Sets the tuple_of_float of this TestModel.


        :param tuple_of_float: The tuple_of_float of this TestModel.
        :type tuple_of_float: List[float]
        """

        self._tuple_of_float = tuple_of_float

    @property
    def set_of_str(self):
        """Gets the set_of_str of this TestModel.


        :return: The set_of_str of this TestModel.
        :rtype: List[str]
        """
        return self._set_of_str

    @set_of_str.setter
    def set_of_str(self, set_of_str):
        """Sets the set_of_str of this TestModel.


        :param set_of_str: The set_of_str of this TestModel.
        :type set_of_str: List[str]
        """

        self._set_of_str = set_of_str

    @property
    def set_of_int(self):
        """Gets the set_of_int of this TestModel.


        :return: The set_of_int of this TestModel.
        :rtype: List[int]
        """
        return self._set_of_int

    @set_of_int.setter
    def set_of_int(self, set_of_int):
        """Sets the set_of_int of this TestModel.


        :param set_of_int: The set_of_int of this TestModel.
        :type set_of_int: List[int]
        """

        self._set_of_int = set_of_int

    @property
    def set_of_float(self):
        """Gets the set_of_float of this TestModel.


        :return: The set_of_float of this TestModel.
        :rtype: List[float]
        """
        return self._set_of_float

    @set_of_float.setter
    def set_of_float(self, set_of_float):
        """Sets the set_of_float of this TestModel.


        :param set_of_float: The set_of_float of this TestModel.
        :type set_of_float: List[float]
        """

        self._set_of_float = set_of_float
