# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from . import util


class TestModelSingleDict(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    openapi_types = {'param': str}

    attribute_map = {'param': 'param'}

    def __init__(self, param='string'):  # noqa: E501
        """TestModelSingleDict - a model defined in OpenAPI

        :param param: The param of this TestModelSingleDict.  # noqa: E501
        :type param: str
        """

        self.param = param

    @classmethod
    def from_dict(cls, dikt) -> 'TestModelSingleDict':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TestModel_single_dict of this TestModelSingleDict.  # noqa: E501
        :rtype: TestModelSingleDict
        """
        return util.deserialize_model(dikt, cls)

    @property
    def param(self):
        """Gets the param of this TestModelSingleDict.


        :return: The param of this TestModelSingleDict.
        :rtype: str
        """
        return self._param

    @param.setter
    def param(self, param):
        """Sets the param of this TestModelSingleDict.


        :param param: The param of this TestModelSingleDict.
        :type param: str
        """

        self._param = param
