# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from . import util


class FlatObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    openapi_types = {'text': str, 'number': float}

    attribute_map = {'text': 'text', 'number': 'number'}

    def __init__(self, text='string', number=123.45):  # noqa: E501
        """FlatObject - a model defined in OpenAPI

        :param text: The text of this FlatObject.  # noqa: E501
        :type text: str
        :param number: The number of this FlatObject.  # noqa: E501
        :type number: float
        """

        self.text = text
        self.number = number

    @classmethod
    def from_dict(cls, dikt) -> 'FlatObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FlatObject of this FlatObject.  # noqa: E501
        :rtype: FlatObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this FlatObject.


        :return: The text of this FlatObject.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this FlatObject.


        :param text: The text of this FlatObject.
        :type text: str
        """

        self._text = text

    @property
    def number(self):
        """Gets the number of this FlatObject.


        :return: The number of this FlatObject.
        :rtype: float
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this FlatObject.


        :param number: The number of this FlatObject.
        :type number: float
        """

        self._number = number
