# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .flat_object import FlatObject
from . import util


class NestedObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    openapi_types = {
        'single_str': str,
        'flat_object': FlatObject,
        'list_of_flat_objects': List[FlatObject],
    }

    attribute_map = {
        'single_str': 'single_str',
        'flat_object': 'flat_object',
        'list_of_flat_objects': 'list_of_flat_objects',
    }

    def __init__(
        self, single_str='string', flat_object=None, list_of_flat_objects=[]
    ):  # noqa: E501
        """NestedObject - a model defined in OpenAPI

        :param single_str: The single_str of this NestedObject.  # noqa: E501
        :type single_str: str
        :param flat_object: The flat_object of this NestedObject.  # noqa: E501
        :type flat_object: FlatObject
        :param list_of_flat_objects: The list_of_flat_objects of this NestedObject.  # noqa: E501
        :type list_of_flat_objects: List[FlatObject]
        """

        self.single_str = single_str
        self.flat_object = flat_object
        self.list_of_flat_objects = list_of_flat_objects

    @classmethod
    def from_dict(cls, dikt) -> 'NestedObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NestedObject of this NestedObject.  # noqa: E501
        :rtype: NestedObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def single_str(self):
        """Gets the single_str of this NestedObject.


        :return: The single_str of this NestedObject.
        :rtype: str
        """
        return self._single_str

    @single_str.setter
    def single_str(self, single_str):
        """Sets the single_str of this NestedObject.


        :param single_str: The single_str of this NestedObject.
        :type single_str: str
        """

        self._single_str = single_str

    @property
    def flat_object(self):
        """Gets the flat_object of this NestedObject.


        :return: The flat_object of this NestedObject.
        :rtype: FlatObject
        """
        return self._flat_object

    @flat_object.setter
    def flat_object(self, flat_object):
        """Sets the flat_object of this NestedObject.


        :param flat_object: The flat_object of this NestedObject.
        :type flat_object: FlatObject
        """

        self._flat_object = flat_object

    @property
    def list_of_flat_objects(self):
        """Gets the list_of_flat_objects of this NestedObject.


        :return: The list_of_flat_objects of this NestedObject.
        :rtype: List[FlatObject]
        """
        return self._list_of_flat_objects

    @list_of_flat_objects.setter
    def list_of_flat_objects(self, list_of_flat_objects):
        """Sets the list_of_flat_objects of this NestedObject.


        :param list_of_flat_objects: The list_of_flat_objects of this NestedObject.
        :type list_of_flat_objects: List[FlatObject]
        """

        self._list_of_flat_objects = list_of_flat_objects
