# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .ac_type import AcType
import re
from . import util

from .ac_type import AcType  # noqa: E501
import re  # noqa: E501

class Airplane(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, ac_type=None, callsign=None, engine_count=None, manufacturer=None):  # noqa: E501
        """Airplane - a model defined in OpenAPI

        :param id: The id of this Airplane.  # noqa: E501
        :type id: str
        :param ac_type: The ac_type of this Airplane.  # noqa: E501
        :type ac_type: AcType
        :param callsign: The callsign of this Airplane.  # noqa: E501
        :type callsign: str
        :param engine_count: The engine_count of this Airplane.  # noqa: E501
        :type engine_count: int
        :param manufacturer: The manufacturer of this Airplane.  # noqa: E501
        :type manufacturer: str
        """
        self.openapi_types = {
            'id': str,
            'ac_type': AcType,
            'callsign': str,
            'engine_count': int,
            'manufacturer': str
        }

        self.attribute_map = {
            'id': 'id',
            'ac_type': 'ac_type',
            'callsign': 'callsign',
            'engine_count': 'engine_count',
            'manufacturer': 'manufacturer'
        }

        self.id = id
        self.ac_type = ac_type
        self.callsign = callsign
        self.engine_count = engine_count
        self.manufacturer = manufacturer

    @classmethod
    def from_dict(cls, dikt) -> 'Airplane':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Airplane of this Airplane.  # noqa: E501
        :rtype: Airplane
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Airplane.


        :return: The id of this Airplane.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Airplane.


        :param id: The id of this Airplane.
        :type id: str
        """

        self._id = id

    @property
    def ac_type(self):
        """Gets the ac_type of this Airplane.


        :return: The ac_type of this Airplane.
        :rtype: AcType
        """
        return self._ac_type

    @ac_type.setter
    def ac_type(self, ac_type):
        """Sets the ac_type of this Airplane.


        :param ac_type: The ac_type of this Airplane.
        :type ac_type: AcType
        """

        self._ac_type = ac_type

    @property
    def callsign(self):
        """Gets the callsign of this Airplane.


        :return: The callsign of this Airplane.
        :rtype: str
        """
        return self._callsign

    @callsign.setter
    def callsign(self, callsign):
        """Sets the callsign of this Airplane.


        :param callsign: The callsign of this Airplane.
        :type callsign: str
        """
        if callsign is not None and len(callsign) > 7:
            raise ValueError("Invalid value for `callsign`, length must be less than or equal to `7`")  # noqa: E501
        if callsign is not None and not re.search(r'^[A-Z0-9]*$', callsign):  # noqa: E501
            raise ValueError("Invalid value for `callsign`, must be a follow pattern or equal to `/^[A-Z0-9]*$/`")  # noqa: E501

        self._callsign = callsign

    @property
    def engine_count(self):
        """Gets the engine_count of this Airplane.


        :return: The engine_count of this Airplane.
        :rtype: int
        """
        return self._engine_count

    @engine_count.setter
    def engine_count(self, engine_count):
        """Sets the engine_count of this Airplane.


        :param engine_count: The engine_count of this Airplane.
        :type engine_count: int
        """

        self._engine_count = engine_count

    @property
    def manufacturer(self):
        """Gets the manufacturer of this Airplane.


        :return: The manufacturer of this Airplane.
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this Airplane.


        :param manufacturer: The manufacturer of this Airplane.
        :type manufacturer: str
        """

        self._manufacturer = manufacturer
