# coding: utf-8

from __future__ import absolute_import

import re  # noqa: E501
from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from . import util
from .airplane import Airplane  # noqa: E501
from .base_model_ import Model


class Flight(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(
        self,
        id=None,
        airplane=None,
        departure_time=None,
        arrival_time=None,
        departure_icao=None,
        arrival_icao=None,
    ):  # noqa: E501
        """Flight - a model defined in OpenAPI

        :param id: The id of this Flight.  # noqa: E501
        :type id: str
        :param airplane: The airplane of this Flight.  # noqa: E501
        :type airplane: Airplane
        :param departure_time: The departure_time of this Flight.  # noqa: E501
        :type departure_time: datetime
        :param arrival_time: The arrival_time of this Flight.  # noqa: E501
        :type arrival_time: datetime
        :param departure_icao: The departure_icao of this Flight.  # noqa: E501
        :type departure_icao: str
        :param arrival_icao: The arrival_icao of this Flight.  # noqa: E501
        :type arrival_icao: str
        """
        self.openapi_types = {
            'id': str,
            'airplane': Airplane,
            'departure_time': datetime,
            'arrival_time': datetime,
            'departure_icao': str,
            'arrival_icao': str,
        }

        self.attribute_map = {
            'id': 'id',
            'airplane': 'airplane',
            'departure_time': 'departure_time',
            'arrival_time': 'arrival_time',
            'departure_icao': 'departure_icao',
            'arrival_icao': 'arrival_icao',
        }

        self.id = id
        self.airplane = airplane
        self.departure_time = departure_time
        self.arrival_time = arrival_time
        self.departure_icao = departure_icao
        self.arrival_icao = arrival_icao

    @classmethod
    def from_dict(cls, dikt) -> 'Flight':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Flight of this Flight.  # noqa: E501
        :rtype: Flight
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Flight.


        :return: The id of this Flight.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Flight.


        :param id: The id of this Flight.
        :type id: str
        """

        self._id = id

    @property
    def airplane(self):
        """Gets the airplane of this Flight.


        :return: The airplane of this Flight.
        :rtype: Airplane
        """
        return self._airplane

    @airplane.setter
    def airplane(self, airplane):
        """Sets the airplane of this Flight.


        :param airplane: The airplane of this Flight.
        :type airplane: Airplane
        """

        self._airplane = airplane

    @property
    def departure_time(self):
        """Gets the departure_time of this Flight.


        :return: The departure_time of this Flight.
        :rtype: datetime
        """
        return self._departure_time

    @departure_time.setter
    def departure_time(self, departure_time):
        """Sets the departure_time of this Flight.


        :param departure_time: The departure_time of this Flight.
        :type departure_time: datetime
        """

        self._departure_time = departure_time

    @property
    def arrival_time(self):
        """Gets the arrival_time of this Flight.


        :return: The arrival_time of this Flight.
        :rtype: datetime
        """
        return self._arrival_time

    @arrival_time.setter
    def arrival_time(self, arrival_time):
        """Sets the arrival_time of this Flight.


        :param arrival_time: The arrival_time of this Flight.
        :type arrival_time: datetime
        """

        self._arrival_time = arrival_time

    @property
    def departure_icao(self):
        """Gets the departure_icao of this Flight.


        :return: The departure_icao of this Flight.
        :rtype: str
        """
        return self._departure_icao

    @departure_icao.setter
    def departure_icao(self, departure_icao):
        """Sets the departure_icao of this Flight.


        :param departure_icao: The departure_icao of this Flight.
        :type departure_icao: str
        """
        if departure_icao is not None and not re.search(
            r'^[A-Z]{4}$', departure_icao
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `departure_icao`, must be a follow pattern or equal to `/^[A-Z]{4}$/`"
            )  # noqa: E501

        self._departure_icao = departure_icao

    @property
    def arrival_icao(self):
        """Gets the arrival_icao of this Flight.


        :return: The arrival_icao of this Flight.
        :rtype: str
        """
        return self._arrival_icao

    @arrival_icao.setter
    def arrival_icao(self, arrival_icao):
        """Sets the arrival_icao of this Flight.


        :param arrival_icao: The arrival_icao of this Flight.
        :type arrival_icao: str
        """
        if arrival_icao is not None and not re.search(
            r'^[A-Z]{4}$', arrival_icao
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `arrival_icao`, must be a follow pattern or equal to `/^[A-Z]{4}$/`"
            )  # noqa: E501

        self._arrival_icao = arrival_icao
