# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from . import util
from .base_model_ import Model


class JsonPatch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, op=None, path=None, value=None):  # noqa: E501
        """JsonPatch - a model defined in OpenAPI

        :param op: The op of this JsonPatch.  # noqa: E501
        :type op: str
        :param path: The path of this JsonPatch.  # noqa: E501
        :type path: str
        :param value: The value of this JsonPatch.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {'op': str, 'path': str, 'value': str}

        self.attribute_map = {'op': 'op', 'path': 'path', 'value': 'value'}

        self._op = op
        self._path = path
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'JsonPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JsonPatch of this JsonPatch.  # noqa: E501
        :rtype: JsonPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def op(self):
        """Gets the op of this JsonPatch.


        :return: The op of this JsonPatch.
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op):
        """Sets the op of this JsonPatch.


        :param op: The op of this JsonPatch.
        :type op: str
        """
        allowed_values = ["add", "remove", "replace"]  # noqa: E501
        if op not in allowed_values:
            raise ValueError(
                "Invalid value for `op` ({0}), must be one of {1}".format(
                    op, allowed_values
                )
            )

        self._op = op

    @property
    def path(self):
        """Gets the path of this JsonPatch.


        :return: The path of this JsonPatch.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this JsonPatch.


        :param path: The path of this JsonPatch.
        :type path: str
        """
        if path is None:
            raise ValueError(
                "Invalid value for `path`, must not be `None`"
            )  # noqa: E501

        self._path = path

    @property
    def value(self):
        """Gets the value of this JsonPatch.


        :return: The value of this JsonPatch.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this JsonPatch.


        :param value: The value of this JsonPatch.
        :type value: str
        """

        self._value = value
