# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from . import util
from .base_model_ import Model


class TrackPoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    openapi_types: dict[str, type] = {
        'latitude': float,
        'longitude': float,
        'altitude': float,
        'heading': float,
        'timestamp': datetime,
    }

    attribute_map = {
        'latitude': 'latitude',
        'longitude': 'longitude',
        'altitude': 'altitude',
        'heading': 'heading',
        'timestamp': 'timestamp',
    }

    def __init__(
        self,
        latitude=None,
        longitude=None,
        altitude=None,
        heading=None,
        timestamp=None,
    ):  # noqa: E501
        """TrackPoint - a model defined in OpenAPI

        :param latitude: The latitude of this TrackPoint.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this TrackPoint.  # noqa: E501
        :type longitude: float
        :param altitude: The altitude of this TrackPoint.  # noqa: E501
        :type altitude: float
        :param heading: The heading of this TrackPoint.  # noqa: E501
        :type heading: float
        :param timestamp: The timestamp of this TrackPoint.  # noqa: E501
        :type timestamp: datetime
        """
        self.latitude = latitude
        self.longitude = longitude
        self.altitude = altitude
        self.heading = heading
        self.timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'TrackPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackPoint of this TrackPoint.  # noqa: E501
        :rtype: TrackPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def latitude(self):
        """Gets the latitude of this TrackPoint.


        :return: The latitude of this TrackPoint.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this TrackPoint.


        :param latitude: The latitude of this TrackPoint.
        :type latitude: float
        """
        if latitude is None:
            raise ValueError(
                "Invalid value for `latitude`, must not be `None`"
            )  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this TrackPoint.


        :return: The longitude of this TrackPoint.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this TrackPoint.


        :param longitude: The longitude of this TrackPoint.
        :type longitude: float
        """
        if longitude is None:
            raise ValueError(
                "Invalid value for `longitude`, must not be `None`"
            )  # noqa: E501

        self._longitude = longitude

    @property
    def altitude(self):
        """Gets the altitude of this TrackPoint.


        :return: The altitude of this TrackPoint.
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this TrackPoint.


        :param altitude: The altitude of this TrackPoint.
        :type altitude: float
        """
        if altitude is None:
            raise ValueError(
                "Invalid value for `altitude`, must not be `None`"
            )  # noqa: E501

        self._altitude = altitude

    @property
    def heading(self):
        """Gets the heading of this TrackPoint.


        :return: The heading of this TrackPoint.
        :rtype: float
        """
        return self._heading

    @heading.setter
    def heading(self, heading):
        """Sets the heading of this TrackPoint.


        :param heading: The heading of this TrackPoint.
        :type heading: float
        """
        if heading is None:
            raise ValueError(
                "Invalid value for `heading`, must not be `None`"
            )  # noqa: E501

        self._heading = heading

    @property
    def timestamp(self):
        """Gets the timestamp of this TrackPoint.


        :return: The timestamp of this TrackPoint.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this TrackPoint.


        :param timestamp: The timestamp of this TrackPoint.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
