# coding: utf-8

from __future__ import absolute_import

from typing import List  # noqa: F401

from . import util
from .base_model_ import Model
from .flight import Flight  # noqa: E501
from .track_point import TrackPoint  # noqa: E501


class Track(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, trackpoints=None, flight=None):  # noqa: E501
        """Track - a model defined in OpenAPI

        :param id: The id of this Track.  # noqa: E501
        :type id: str
        :param trackpoints: The trackpoints of this Track.  # noqa: E501
        :type trackpoints: List[TrackPoint]
        :param flight: The flight of this Track.  # noqa: E501
        :type flight: Flight
        """
        self.openapi_types = {
            'id': str,
            'trackpoints': List[TrackPoint],
            'flight': Flight,
        }

        self.attribute_map = {
            'id': 'id',
            'trackpoints': 'trackpoints',
            'flight': 'flight',
        }

        self.id = id
        self.trackpoints = trackpoints
        self.flight = flight

    @classmethod
    def from_dict(cls, dikt) -> 'Track':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Track of this Track.  # noqa: E501
        :rtype: Track
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Track.


        :return: The id of this Track.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Track.


        :param id: The id of this Track.
        :type id: str
        """

        self._id = id

    @property
    def trackpoints(self):
        """Gets the trackpoints of this Track.


        :return: The trackpoints of this Track.
        :rtype: List[TrackPoint]
        """
        return self._trackpoints

    @trackpoints.setter
    def trackpoints(self, trackpoints):
        """Sets the trackpoints of this Track.


        :param trackpoints: The trackpoints of this Track.
        :type trackpoints: List[TrackPoint]
        """

        self._trackpoints = trackpoints

    @property
    def flight(self):
        """Gets the flight of this Track.


        :return: The flight of this Track.
        :rtype: Flight
        """
        return self._flight

    @flight.setter
    def flight(self, flight):
        """Sets the flight of this Track.


        :param flight: The flight of this Track.
        :type flight: Flight
        """

        self._flight = flight
